# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d217332e65054e8ef3bc6b78e6e4c529571c799820919bc5ef07d6d35bf19cc8421318699153c89458190332db75cae36a2bce04b92c069c83eec528aa4abb65

test:
  secret_key_base: 73c5e6996f7d41524fac8a588545fc0e287e72994fa913eba571e640dceb422fc28221fb30fc4129f22ccfb46fba35fa702575693daf47ac96b4b44718805bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
